version: '2'

services:
  nginx-proxy:
    build: ./IdeaManager_RP
    image: ideamanager_rp
    ports:
      - "80:80"
    volumes: 
      - /tmp/IdeaManager_RP/conf:/etc/nginx/sites-enabled
    links:
      - ideaManWeb

  ideaManWeb:
    build: ./IdeaManager_FE
    image: ideamanager_fe
    expose: 
      - "80"
